### ISSUE TITLE
集保中心股權分散表無法正常取得

### ISSUE THREAD

**Issue by virus-warnning** [virus-warnning/twnews#110]
**問題描述**

* tdcc.py 的 get_argument() 寫錯，導致集保中心資料抓不到
* Linode 使用 IPv6 位址導致連不上集保中心

**重現方法**

用下列步驟可以讓程式爆掉
1. python3 -m twnews.finance.tdcc

**預期行為**

```
[17:53:24] common  | DEBUG   | 建立新的 session
[17:53:26] finance | INFO    | 已更新 TDCC 20200417 的股權分散表
[17:53:26] news    | DEBUG   | 使用快取目錄: /Users/raymond/.twnews/cache/tdcc
[17:53:27] finance | DEBUG   | 已儲存 TDCC 2020-04-17 的股權分散資料 5000 筆
...
```

**實際行為**

結果變成這樣 ...
```bash
python3 -m twnews.finance.tdcc update
[17:46:11] finance | ERROR   | 無法識別的動作 /Users/raymond/repos/twnews/twnews/finance/tdcc.py
```

**系統環境**

 - Python: [至少要 3.5 以上喔]
 - OS: [例如 Ubuntu 18.04]

**Comment by virus-warnning** [comment]
解決 get_argument 問題後又出現這個問題

```
python3 -m twnews.finance.tdcc update
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/twnews/twnews/finance/__init__.py", line 134, in fucking_get
    resp = session.get(url, params=params)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/twnews/twnews/finance/tdcc.py", line 166, in <module>
    main()
  File "/root/twnews/twnews/finance/tdcc.py", line 159, in main
    sync_dataset()
  File "/root/twnews/twnews/finance/tdcc.py", line 140, in sync_dataset
    changed = backup_dist()
  File "/root/twnews/twnews/finance/tdcc.py", line 134, in backup_dist
    return fucking_get(hook, url, params)
  File "/root/twnews/twnews/finance/__init__.py", line 141, in fucking_get
    raise NetworkException(msg)
twnews.exceptions.NetworkException
```

**Comment by virus-warnning** [comment]
在兩個環境上測試 wget 下載股權分散表，發現日本 Linode 會使用 IPv6 而且無法連線

```sh
$ wget -O tdcc0417.csv https://smart.tdcc.com.tw/opendata/getOD.ashx?id=1-5
# DS218+
Connecting to smart.tdcc.com.tw|61.57.46.211|:443... connected.
# 日本 Linode
Connecting to smart.tdcc.com.tw (smart.tdcc.com.tw)|2001:4420:60b2:0:210:241:84:211|:443... connected.
```

強制使用 IPv4 之後，日本 Linode 也能用了

```sh
$ wget -4 -O tdcc0417.csv https://smart.tdcc.com.tw/opendata/getOD.ashx?id=1-5
Connecting to smart.tdcc.com.tw (smart.tdcc.com.tw)|61.57.46.211|:443... connected.
```

應該要從 requests 參數著手，限制 IPv4 應該就能解決問題

**Comment by virus-warnning** [comment]
寫簡短的測試程式，發現本機 google 正常但 tdcc 無回應

```python
import requests
url = 'https://smart.tdcc.com.tw/opendata/getOD.ashx?id=1-5'
# url = 'https://www.google.com.tw'
resp = requests.get(url)
print(resp.status_code)
```

發現小改一下 user-agent 就過了

```python
import requests

url = 'https://smart.tdcc.com.tw/opendata/getOD.ashx?id=1-5'
# url = 'https://www.google.com.tw'

sess = requests.Session()
sess.headers.update({
    "User-Agent": 'PostmanRuntime/7.24.1'
})
resp = sess.get(url, timeout=3)
print(resp.status_code)
```

不過在 Linode 上一樣不能用

**Comment by virus-warnning** [comment]
使用這一招搞定，第一則回應的解法

https://stackoverflow.com/questions/33046733/force-requests-to-use-ipv4-ipv6
