### ISSUE TITLE
東森的搜尋測試漏掉 proxy_first 參數，導致每週測試失敗

### ISSUE THREAD

**Issue by virus-warnning** [virus-warnning/twnews#52]
**問題描述**

上回增加 proxy_first 參數時，只有加到 soup 測試而漏掉 search 測試

**重現方法**

用下列步驟可以讓程式爆掉
1. python3 -m unittest twnews.tests.search.test_search_ettoday.TestEttoday

**預期行為**

測試程式必須正常

**實際行為**

結果變成這樣 ...
```
EE
======================================================================
ERROR: test_01_filter_title (twnews.tests.search.test_search_ettoday.TestEttoday)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/contrib/pyopenssl.py", line 299, in recv_into
    raise SocketError(str(e))
OSError: (104, 'ECONNRESET')

...
```

**系統環境**

 - Python: 3.5
 - OS: 16.04
-  Linode

**Comment by virus-warnning** [comment]
修改後東森時好時壞，需要繼續觀察或是優化環境

* 確認 tor 正常運作
* 測試前啟動 tor
* 測試後結束 tor

**Comment by virus-warnning** [comment]
NewSearch 的 proxy_first 參數再傳遞給 NewsSoup 之後問題解決
